import React, { useState } from "react";

const API_BASE_URL =
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (import.meta as any).env?.VITE_API_BASE_URL || "http://localhost:3000";

function TestPage() {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<{
    success: boolean;
    imageBase64?: string;
    model?: string;
    elapsedSeconds?: string;
    error?: string;
  } | null>(null);

  async function runTest() {
    setLoading(true);
    setResult(null);
    try {
      const response = await fetch(`${API_BASE_URL}/api/test-google-ai`);
      const data = (await response.json()) as {
        success: boolean;
        imageBase64?: string;
        model?: string;
        elapsedSeconds?: string;
        error?: string;
      };
      setResult(data);
    } catch (err) {
      setResult({
        success: false,
        error: err instanceof Error ? err.message : String(err),
      });
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen bg-gray-900 text-white flex flex-col items-center justify-start p-8 gap-6">
      <h1 className="text-3xl font-bold">Google AI Studio — Test Page</h1>
      <p className="text-gray-400 text-center max-w-lg">
        Sends a simple text-only prompt to{" "}
        <code className="bg-gray-800 px-1 rounded">gemini-2.5-flash-image</code>{" "}
        and displays the generated image. No template fetch, no auth required.
      </p>

      <button
        type="button"
        onClick={() => void runTest()}
        disabled={loading}
        className="px-8 py-4 bg-yellow-500 hover:bg-yellow-400 disabled:bg-gray-600 text-black font-bold text-xl rounded-lg transition-colors cursor-pointer"
      >
        {loading ? "Generating..." : "Run Test"}
      </button>

      {loading && (
        <p className="text-yellow-400 animate-pulse text-lg">
          Calling Google AI Studio... (may take 15–60s)
        </p>
      )}

      {result && (
        <div className="w-full max-w-2xl flex flex-col gap-4">
          <div
            className={`p-4 rounded-lg font-mono text-sm ${
              result.success
                ? "bg-green-900 text-green-200"
                : "bg-red-900 text-red-200"
            }`}
          >
            <p>
              <strong>Status:</strong> {result.success ? "SUCCESS" : "FAILED"}
            </p>
            {result.model && (
              <p>
                <strong>Model:</strong> {result.model}
              </p>
            )}
            {result.elapsedSeconds && (
              <p>
                <strong>Elapsed:</strong> {result.elapsedSeconds}s
              </p>
            )}
            {result.error && (
              <p>
                <strong>Error:</strong> {result.error}
              </p>
            )}
          </div>

          {result.imageBase64 && (
            <div className="flex flex-col items-center gap-2">
              <p className="text-gray-400 text-sm">Generated image:</p>
              <img
                src={result.imageBase64}
                alt="Generated by Google AI"
                className="max-w-full rounded-lg border border-gray-600"
              />
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default TestPage;
